### ISSUE TITLE
At mobile widths, the top nav dropdowns do not appear immediately: you have to scroll the area to see the selections

### ISSUE THREAD

**Issue by faunaee** [DocOps/asciidocsy-jekyll-theme#15]
<img width="450" alt="mobile-top-nav" src="https://user-images.githubusercontent.com/46354154/119176308-c9f59700-ba1f-11eb-9ae5-e4187fd1cd3b.png">

**Comment by briandominick** [comment]
I have been unable to reproduce this problem. Can you give me more info on the platform?

Here's what I'm seeing:

![asciidocsy-mobile-topnav-opera-desktop](https://user-images.githubusercontent.com/1264177/130295783-fd8945ad-7bb5-4694-b331-5b9f06fddf6a.png)

![asciidocsy-mobile-topnav-firefox-desktop](https://user-images.githubusercontent.com/1264177/130295823-2beaec33-a4fa-48f5-8c6d-e63d6e418dda.png)

I tried in a few other environments that for some reason GH won't accept the .png screenshots from, but they all look the same.

I'm going to work on the other irregularities shown here, but I can't reproduce the topnav effect.

Also is there any chance you know what's currently state-of-the-art FOSS method of evaluating a URL through various browser engines?

**Comment by faunaee** [comment]
Firefox 91.01 on macOS 11.4, using Responsive Design Mode with iPhone 6/7/8 selected.

In this screenshot, I've clicked on "About", so you can see how the dropdown's items get cropped by the header:

<img width="458" alt="Screen Shot 2021-08-20 at 3 20 17 PM" src="https://user-images.githubusercontent.com/46354154/130298894-bbcb4e54-f82c-49c9-906d-d6f676398bf0.png">

**Comment by briandominick** [comment]
Okay I figured it out. I think I fixed this and your other ticket (#14) in one PR (#75). I'm going to assign you to review when the staging site builds, if you would be so kind...

**Comment by faunaee** [comment]
LGTM! 👍
