### ISSUE TITLE
add docs for installing theme as submodule

### ISSUE THREAD

**Issue by capsulecorplab** [DocOps/asciidocsy-jekyll-theme#43]
Having the theme maintained as a submodule would allow for easier updates to the theme as new releases get published

**Comment by briandominick** [comment]
I have not seen this done before, and I'm not sure it has any advantages over using the theme as a Ruby gem, which I plan to release (probably in 0.3.0 later this summer). The gem lets us update the theme in this repo and gives the user control of when they sync updates to it, which I think is what you're looking for. But gemified themes also let you override theme files very easily without placing any of them in your workspace. If there are advantages of using it as a submodule, I'm happy to look into it.

**Comment by capsulecorplab** [comment]
I can't speak for Jekyll, but the use of submodules for maintaining themes is a fairly prevalent workflow in Hugo. In any case, a Ruby gem should satisfy the fundamental use case of updating/reverting theme versions/releases, albeit using the gem/bundler workflow.
