### ISSUE TITLE
How to adjust site footer height

### ISSUE THREAD

**Issue by capsulecorplab** [DocOps/asciidocsy-jekyll-theme#56]
There's a lot of unoccupied vertical space in the site footer that I wouldn't mind shortening ![Screenshot from 2021-07-08 13-42-44](https://user-images.githubusercontent.com/14095576/124981295-a055f680-dff2-11eb-9bfd-0aa681ddbc5c.png)

**Comment by briandominick** [comment]
This is best done by adding style definitions to your `css/custom.css` file. I will also be adding some fine-tuning for this block in the 0.2.0 configuration.

For example, this would get rid of the padding above the lines of text there:
```
.footer-strings {
    margin-top: 0;
}
```

Also try altering the `padding-bottom` for the `footer` element itself.

```
footer {
  padding-bottom: 20px;
}
```
