### ISSUE TITLE
removing Gemfile.lock from .gitignore

### ISSUE THREAD

**Issue by capsulecorplab** [DocOps/asciidocsy-jekyll-theme#58]
I don't think it makes sense to have `Gemfile.lock` in `.gitignore`, since the point of the lock file is to provide a reproducible build of dependencies needed to run a working site. I spent a couple of hours trying to debug why `bundler` was producing inconsistent builds when experimenting between jekyll 3.8 & 4.2, committing relevant changes as I go (as one should), until I noticed `git` wasn't tracking changes to `Gemfile.lock` after running `bundle lock`.
https://github.com/DocOps/asciidocsy-jekyll-theme/blob/623eeabb1a3c2a370c504f2c42414b1c7efca34c/.gitignore#L2

**Comment by briandominick** [comment]
You're 100% right, Sean. This is an artifact from the original that I forked (https://github.com/vsoch/docsy-jekyll/blob/master/.gitignore), but I'm surprised I did not notice. Slipping this into 0.2.0 that I'm releasing today. If you need help upgrading let me know.

**Comment by briandominick** [comment]
I merged this change into the 0.2.0 trunk. I have one more feature and some docs to commit today, none of which should affect current functionality on trunk very much. If you want to test that out a bit early you're welcome.

https://github.com/DocOps/asciidocsy-jekyll-theme/tree/trunk-0.2.0

**Comment by capsulecorplab** [comment]
Cool! I may test it with the [docker image for supporting asciidocsy](https://github.com/capsulecorplab/asciidoctor-extended/pull/3) I just published last night 😁
